### ISSUE TITLE
file.rmRf() works incorrectly with symlinks

### ISSUE THREAD

**Issue by welearnednothing** [mde/utilities#24]
Originally [file against Jake](https://github.com/jakejs/jake/issues/161).

When a directory that is a symlink or contains a symlink is passed into `file.rmRf()`, the symlink is not deleted and the contents of any linked folders are deleted. Dangerous behavior that does not accurately mirror `rm -rf` in Bash.

I have a PR coming with tests that document steps to reproduce and expected results.

**Comment by mde** [comment]
Whoa, nice find, and sorry if it caused some heartache. Any chance of providing a fix along with this?

**Comment by mde** [comment]
Oh, I see you've submitted a fix too. Awesome!
